-- MySQL Script generated by MySQL Workbench
-- Wed Sep  6 02:53:29 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`UsuarioRegistrado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`UsuarioRegistrado` (
  `idUsuarioRegistrado` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `UsuarioAfiliado_IdUsuarioAfiliado` INT NOT NULL,
  PRIMARY KEY (`idUsuarioRegistrado`, `UsuarioAfiliado_IdUsuarioAfiliado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`GrupoFamiliar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`GrupoFamiliar` (
  `idGrupoFamiliar` INT NOT NULL,
  `UsuarioAfiliado_copy1_IdUsuarioAfiliado` INT NOT NULL,
  PRIMARY KEY (`idGrupoFamiliar`, `UsuarioAfiliado_copy1_IdUsuarioAfiliado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empresa` (
  `idEmpresa` INT NOT NULL AUTO_INCREMENT,
  `NombreEmpresa` VARCHAR(45) NOT NULL,
  `NroCUIL` VARCHAR(45) NOT NULL,
  `emailEmpresa` VARCHAR(45) NULL,
  `UsuarioAfiliado_IdUsuarioAfiliado` INT NULL,
  PRIMARY KEY (`idEmpresa`, `UsuarioAfiliado_IdUsuarioAfiliado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`UsuarioAfiliado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`UsuarioAfiliado` (
  `IdUsuarioAfiliado` INT NOT NULL AUTO_INCREMENT,
  `Nombres` VARCHAR(45) NOT NULL,
  `Apellidos` VARCHAR(45) NOT NULL,
  `DNI` INT NOT NULL,
  `Nacimiento` DATE NOT NULL,
  `Afiliacion` DATE NOT NULL,
  `GrupoFamiliar_idGrupoFamiliar` INT NOT NULL,
  `Empresa_UsuarioAfiliado_IdUsuarioAfiliado` INT NOT NULL,
  `UsuarioRegistrado_idUsuarioRegistrado` INT NOT NULL,
  PRIMARY KEY (`IdUsuarioAfiliado`, `Empresa_UsuarioAfiliado_IdUsuarioAfiliado`),
  INDEX `fk_UsuarioAfiliado_GrupoFamiliar_idx` (`GrupoFamiliar_idGrupoFamiliar` ASC) VISIBLE,
  INDEX `fk_UsuarioAfiliado_Empresa1_idx` (`Empresa_UsuarioAfiliado_IdUsuarioAfiliado` ASC) VISIBLE,
  INDEX `fk_UsuarioAfiliado_UsuarioRegistrado1_idx` (`UsuarioRegistrado_idUsuarioRegistrado` ASC) VISIBLE,
  CONSTRAINT `fk_UsuarioAfiliado_GrupoFamiliar`
    FOREIGN KEY (`GrupoFamiliar_idGrupoFamiliar`)
    REFERENCES `mydb`.`GrupoFamiliar` (`idGrupoFamiliar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UsuarioAfiliado_Empresa1`
    FOREIGN KEY (`Empresa_UsuarioAfiliado_IdUsuarioAfiliado`)
    REFERENCES `mydb`.`Empresa` (`UsuarioAfiliado_IdUsuarioAfiliado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UsuarioAfiliado_UsuarioRegistrado1`
    FOREIGN KEY (`UsuarioRegistrado_idUsuarioRegistrado`)
    REFERENCES `mydb`.`UsuarioRegistrado` (`idUsuarioRegistrado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Credencial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Credencial` (
  `idCredencial` INT NOT NULL,
  `Emision` DATE NOT NULL,
  `Vencimiento` DATE NOT NULL,
  `UsuarioAfiliado_IdUsuarioAfiliado` INT NOT NULL,
  PRIMARY KEY (`idCredencial`, `UsuarioAfiliado_IdUsuarioAfiliado`),
  INDEX `fk_Credencial_UsuarioAfiliado1_idx` (`UsuarioAfiliado_IdUsuarioAfiliado` ASC) VISIBLE,
  CONSTRAINT `fk_Credencial_UsuarioAfiliado1`
    FOREIGN KEY (`UsuarioAfiliado_IdUsuarioAfiliado`)
    REFERENCES `mydb`.`UsuarioAfiliado` (`IdUsuarioAfiliado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MiembroGrupoFamiliar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MiembroGrupoFamiliar` (
  `IdMiembroGrupoFamiliar` INT NOT NULL AUTO_INCREMENT,
  `NombresMGF` VARCHAR(45) NOT NULL,
  `ApellidosMGF` VARCHAR(45) NOT NULL,
  `DNI_MGF` INT NOT NULL,
  `NacimientoMGF` DATE NOT NULL,
  `AfiliacionMGF` DATE NOT NULL,
  `GrupoFamiliar_idGrupoFamiliar` INT NOT NULL,
  `Credencial_idCredencial` INT NOT NULL,
  PRIMARY KEY (`IdMiembroGrupoFamiliar`, `GrupoFamiliar_idGrupoFamiliar`, `Credencial_idCredencial`),
  INDEX `fk_MiembroGrupoFamiliar_GrupoFamiliar1_idx` (`GrupoFamiliar_idGrupoFamiliar` ASC) VISIBLE,
  INDEX `fk_MiembroGrupoFamiliar_Credencial1_idx` (`Credencial_idCredencial` ASC) VISIBLE,
  CONSTRAINT `fk_MiembroGrupoFamiliar_GrupoFamiliar1`
    FOREIGN KEY (`GrupoFamiliar_idGrupoFamiliar`)
    REFERENCES `mydb`.`GrupoFamiliar` (`idGrupoFamiliar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MiembroGrupoFamiliar_Credencial1`
    FOREIGN KEY (`Credencial_idCredencial`)
    REFERENCES `mydb`.`Credencial` (`idCredencial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
